apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cluster-compliance
webhooks:
  - name: "{{ .Values.webhook.name }}"
    rules:
      - operations: ["CREATE","DELETE","UPDATE"]
        apiGroups: [ "apps","batch" ]
        apiVersions: [ "v1" ]
        resources: ["pods", "deployments", "replicasets", "jobs", "statefulsets"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "{{ .Values.webhook.service.namespace }}"
        name: "{{ .Values.webhook.service.name }}"
        path: "{{ .Values.webhook.path }}"
      caBundle: "{{ .Values.webhook.caBundle }}"
    admissionReviewVersions: ["v1", "v1beta1"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5