apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cluster-compliance
webhooks:
  - name: "{{ .Values.webhook.name }}"
    rules:
      - operations: ["CREATE"]
        apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        resources: [ "*" ]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: "{{ .Values.webhook.service.namespace }}"
        name: "{{ .Values.webhook.service.name }}"
        path: "{{ .Values.webhook.path }}"
      caBundle: "{{ .Values.webhook.caBundle }}"
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5