apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cluster-compliance
webhooks:
  - name: "deployment.mutation.svc"
    rules:
      - operations: ["CREATE"]
        apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        resources: [ "*" ]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: kube-system
        name: webhook-server
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSekNDQWkrZ0F3SUJBZ0lVSGs1L2pHelM2TVk1YmZITEtSeGNPWk5FOVlvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tURW5NQ1VHQTFVRUF3d2VkMlZpYUc5dmF5MXpaWEoyWlhJdWEzVmlaUzF6ZVhOMFpXMHVjM1pqTUI0WApEVEkwTURjeE5USXhNamd3TVZvWERUSTBNRGd4TkRJeE1qZ3dNVm93S1RFbk1DVUdBMVVFQXd3ZWQyVmlhRzl2CmF5MXpaWEoyWlhJdWEzVmlaUzF6ZVhOMFpXMHVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVBbnVWaEcyYzBSUldZWmlETy92SDVzZ2E5MXcyM0VWL0xTZzNGNC82RDEvN0x6R0h4WG9NYQpQVms1NWZQM2lMSGt4OXFPOXFvWUFJdStjcldkMS9lRzkrc2xFc3dINzhSOXQzQmNiR1h2RDZqdTh6bEg3QmhUClhzM3lVR3hxM2MyVS9JdE5xWEk1NVRMUlZUTzgxSVJPODREd3ZHMk56eUw2NEFOZkpDSVQzajJHbGErbDNtaVUKTFlRd2lDNnhQVnNTZVdTTTFNSjF4VWk4UVRyK3lNTzkxUkhBL3JlYSt1S3R4MVkxblpDU3M3UURRSjFaQlloZApLNWFJSUdYSHZGeDdsT2pBMGVvQXBZVlEvcFlUTWVIbHZPQldHWkJlU0pZWkJva2FHaE9aUlRMU05uYUVrTlYxClNTazFFbzYrbDJIcWVqT0ZJVjZvN1MxNVBjcHRVTmorclFJREFRQUJvMmN3WlRBTUJnTlZIUk1FQlRBREFRSC8KTUFzR0ExVWREd1FFQXdJRm9EQXBCZ05WSFJFRUlqQWdnaDUzWldKb2IyOXJMWE5sY25abGNpNXJkV0psTFhONQpjM1JsYlM1emRtTXdIUVlEVlIwT0JCWUVGRjlMV2JuekNzajRhTE5DT0pvdGRoTzJtakVKTUEwR0NTcUdTSWIzCkRRRUJDd1VBQTRJQkFRQUdPRmNhSGkxV2J2MjdPczZlN2RLOVJaY2xsbjcwUEl2WnoxeTVldjlvclFibVJOZXkKQnNNVkxRd3BTUEorVExMNE52L3duTEd0ZEtXU2JmOW9yTVkwcDFXQkd4OTlabHpkdERZdW9ibW41WGRQMm1JeApmS0EwY09RL0xNTE5sdjJtSWU1WEpXd2hZNmp1dlNIbWFJQTU4RTZvNnJabzh0UGlWcnRpSkR5UGovVmpKaUlQClRUR0hsd2ZUdFhRMFNDQU9RVmRoM3hDTFh3b0swKzU3MHdvWVBRa09RRjZBdjFpQXYwQk55Mi9VWDkzTXFtNEgKOTRwb0U5OG1ZRGlabGdmeFYva2kzZStiQXBTdHdPNURsQkRxUUNrMklOYW5EaFNxekF1OTAwallHMkJNcUFBWAp0ZVExMDJRS2hZQldXUHlnK1NqcGJoYVVMSVZhVlJnbVo0SnoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 5