apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cluster-compliance
webhooks:
  - name: "deployment.mutation.svc"
    rules:
      - operations: [ "CREATE"]
        apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        resources: [ "*" ]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: kube-system
        name: webhook-server
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSekNDQWkrZ0F3SUJBZ0lVZElhQWtxZWlleFpxbnc2V0NwaGppdUo4WGxNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tURW5NQ1VHQTFVRUF3d2VkMlZpYUc5dmF5MXpaWEoyWlhJdWEzVmlaUzF6ZVhOMFpXMHVjM1pqTUI0WApEVEkwTURjeE1qRXpORGcxTWxvWERUSTBNRGd4TVRFek5EZzFNbG93S1RFbk1DVUdBMVVFQXd3ZWQyVmlhRzl2CmF5MXpaWEoyWlhJdWEzVmlaUzF6ZVhOMFpXMHVjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEEKTUlJQkNnS0NBUUVBemxpM1k0M2FZWFpTQ0wrRklrS1BsYmNpT2tQdGJoOWc5MERTbVB4QmxJRGVMWTM2UjhVeQpZVTBuMXdFTlRIKzJtL2NKd0FRNy9hcmMzZWpYZ2V1MXZhVm5GUXZHRzhRbEMycVVmZGlDUEMyWjVuT1VnQmd6Ck9GZFltQVVaV3FKRWRUbDJxNFJBNGdtdy9HUXZEUkwyc0E1VTQrNGw0MnJTV1ZLRjhlWDZNNjkyU0YvbU1sb0kKMHZCeXA5V3pOemZDeHM5NjRlU3ZxVkZRbUhRRXRiWTBWUXNGdVdBNWdaSEdaeTlmT1AwdXZkcXcrM2swSVcvZgpSQk1RdVJva0s5d3NQUUMyOVBLeUhUbjNyVkNWd3hQanlpdmhaVFJHZVRmc3BxMVFhSG5IVFJQVkg4d2RwcDBpCmlUbHM5MlVmUjQwWVpScDd2MXYrSlZlRmw4TGpUVTdVeVFJREFRQUJvMmN3WlRBTUJnTlZIUk1FQlRBREFRSC8KTUFzR0ExVWREd1FFQXdJRm9EQXBCZ05WSFJFRUlqQWdnaDUzWldKb2IyOXJMWE5sY25abGNpNXJkV0psTFhONQpjM1JsYlM1emRtTXdIUVlEVlIwT0JCWUVGT3FQVXVRQzZndFVqZUZnaitFd1hoSXp0SG5MTUEwR0NTcUdTSWIzCkRRRUJDd1VBQTRJQkFRQU1wTTUzL0txL0NJVmZicFhXd0hxSk96aTFYaVlHSVM4RENZd1VXTEUzWXVYazFhR2IKWVROZURrWUdqekZVYy82enVqWlAyU0NXTEM0bDR1M3lzR29QdFBxdnltK0ZxYjRjY1Z2TG5KRVVJYVJ1ekJhcApVZitYeXpXWVhmdFdTTHZvOXh3ZjdlMHEzT055UTZxWVlqTkhaWDNkNzJrZ01DWUloSS9uTCtJZGYxVDJpYzExCnFuWEtDM2JocjBFWlV1S2FuRGVyNnFUbmRPNFhhVHFQUHBEOGVRVnVSOGZpYUNCelF6VW8xWGh4QU4yR3VNYTQKNEwrQW44N1Y1YWl6c3Q3N2loM0RGNUpQZHBVbWhjS2ZJdDRkS1VVaDUxbXoybnJQMmVsYmlvM0RlWUR4M2FZZApMK3NONjVkakJjZXVobE16WFpCUUY1WGwrdmprTXNtWCtZd1AKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5