apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: "{{ .Chart.Name }}"
  ports:
    - port: 443
      targetPort: 8443